# Generated by Django 5.0.4 on 2024-04-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSISDN', models.CharField(max_length=30)),
                ('IMSI', models.BigIntegerField()),
                ('IMEI', models.BigIntegerField()),
                ('PLAN', models.CharField(max_length=30)),
                ('CALL_TYPE', models.CharField(max_length=30)),
                ('CORRESP_TYPE', models.CharField(max_length=30)),
                ('CORRESP_ISDN', models.CharField(max_length=30)),
                ('DURATION', models.PositiveIntegerField()),
                ('TIME', models.DateTimeField()),
                ('DATE', models.CharField(max_length=30)),
            ],
        ),
    ]
